## Autogenerated by Altium Designer
##
echo If the file wave.do exists in the same directory as this do file. This script will use it to load any saved waveforms.
echo If you wish to add any custom steps after simulation is loaded create a .do file and add it to the project in Altium Designer
vsim apb_wb_bridge.tb_apb_wb_bridge(sim)
view wave
add wave *
view structure
view signals
